name: "python-schedule"

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        # Install required libs
        - name: Install required libraries
          run: |
            pip3 install -r requirements.txt
    
        - name: Run Python script
          run: |
            TG_TOKEN=${{ secrets.TG_TOKEN }} python3 raspiduino/minesweeper.py